# Generated by Django 5.2.5 on 2025-11-06 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("dark", "Dark Theme"),
                            ("light", "Light Theme"),
                            ("auto", "Auto (System)"),
                        ],
                        default="dark",
                        max_length=20,
                    ),
                ),
                ("auto_play_next", models.BooleanField(default=True)),
                (
                    "default_quality",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("1080p", "1080p"),
                            ("720p", "720p"),
                            ("480p", "480p"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("new_movie_alerts", models.BooleanField(default=True)),
                ("public_profile", models.BooleanField(default=False)),
                ("show_watch_history", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
